# Collins Papers
- id: doi:10.1093/cercor/bhy285
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/cercor/29/3/10.1093_cercor_bhy285/3/m_bhy285f01.jpeg?Expires=1730463957&Signature=hKPod0F9HUgQPlitK9STGQPfiHzoD2AQQ2EVndRD1~HtemT4DbzEKZQGMBRXBzrBikDctRhj5c3tViBYy8RWxhdZRELwZpmZf7whzvSz1Enwcx4hqexTPN-2zEzeH9LEMJ8sQF6oQI4xdzBcqDNogjk41rhM7sAcyLEpr9jUututDbjnTAMVOQv5LsF3CUK39pWyhmcM1vjIAw8khjnVvPJQ14tEQERyiWzNK9-DYvANq5B4YBtZi5yOl0PYU0xu~wUh98-rk20uaTEhemLSrrvfum9bFMAzpMjinEdESbwGjqsmEMHzfj1qC6wNJFgx51SY30yyCHrgpmjJ1t37rQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: pubmed:27994147
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5224395/bin/pnas.1616305114fig01.jpg

# Zook Papers
- id: doi:10.1002/aisy.202470032
  remove: true

- id: doi:10.1002/aisy.202300897
  image: https://onlinelibrary.wiley.com/cms/asset/4e5b34f4-c17e-489f-b6e6-ab32249afb3a/aisy202300897-fig-0001-m.jpg

# Fecker Papers
- id: pmid:38878055
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1094715924001065-gr1.jpg

- id: pmid:39205906
  image: https://pubmed.ncbi.nlm.nih.gov/39205906/#&gid=article-figures&pid=fig-1-uid-0
  