# Collins Papers
- id: doi:10.1093/cercor/bhy285
  image: https://academic.oup.com/view-large/figure/149552044/bhy285f01.tif

- id: pubmed:27994147
  image: https://www.ncbi.nlm.nih.gov/pmc/articles/instance/5224395/bin/pnas.1616305114fig01.jpg

# Zook Papers
- id: doi:10.1002/aisy.202470032
  remove: true

- id: doi:10.1002/aisy.202300897
  image: https://onlinelibrary.wiley.com/cms/asset/4e5b34f4-c17e-489f-b6e6-ab32249afb3a/aisy202300897-fig-0001-m.jpg

# Fecker Papers
- id: pmid:38878055
  image: https://ars.els-cdn.com/content/image/1-s2.0-S1094715924001065-gr1.jpg